// In your quick bite data file (e.g., lib/quick-bites/linea-token-burn.ts)
import { QuickBiteData } from '@/lib/types/quickBites';
import { prefetchDNS } from 'react-dom';

const Fusaka: QuickBiteData = {
  title: "Fusaka Upgrade Overview",
  shortTitle: "Fusaka Upgrade",
  subtitle: "Understanding the Fusaka upgrade.",
  content: [
    "# Introduction:",
    "The Fusaka fork continues Ethereum's blob scaling roadmap. Use the charts below to compare blob and gas usage across upgrade windows.",
    " ",

    "# Blob usage & fees by upgrade window",
    "```chart-toggle",
    JSON.stringify({
      title: "Toggle upgrade windows",
      description: "Switch between Fusaka windows and prior upgrades to compare blob usage, targets, and fees.",
      layout: "segmented",
      defaultIndex: 1,
      charts: [
        {
          toggleLabel: "since Fusaka-BPO1 (2025-12-09)",
          type: "line",
          title: "Blob Usage & Fees Since Fusaka-BPO1",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [],
          caption: "Data: growthepie.com quick-bite fusaka timeseries (Fusaka-BPO1 window).",
        },
        {
          toggleLabel: "since Fusaka (2025-12-03)",
          type: "line",
          title: "Blob Usage & Fees Since Fusaka",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1765281600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO1",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries (Fusaka window).",
        },
        {
          toggleLabel: "since Pectra (2025-05-07)",
          type: "line",
          title: "Blob Usage & Fees Since Pectra",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries (Pectra window).",
        },
        {
          toggleLabel: "since Dencun (2024-03-13)",
          type: "line",
          title: "Blob Usage & Fees Since Dencun",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1746576000000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Pectra",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries (Dencun window).",
        },
      ],
    }),
    "```",

    "## Gas usage & fees by upgrade window",
    "```chart-toggle",
    JSON.stringify({
      title: "Toggle upgrade windows",
      description: "Switch between Fusaka windows and prior upgrades to compare gas usage, limits, and base gas fees.",
      layout: "segmented",
      defaultIndex: 1,
      charts: [
        {
          toggleLabel: "since Fusaka-BPO1 (2025-12-09)",
          type: "line",
          title: "Gas Usage & Fees Since Fusaka-BPO1",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [],
          caption: "Data: growthepie.com quick-bite fusaka timeseries gas (Fusaka-BPO1 window).",
        },
        {
          toggleLabel: "since Fusaka (2025-12-03)",
          type: "line",
          title: "Gas Usage & Fees Since Fusaka",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1765281600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO1",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries gas (Fusaka window).",
        },
        {
          toggleLabel: "since Pectra (2025-05-07)",
          type: "line",
          title: "Gas Usage & Fees Since Pectra",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries gas (Pectra window).",
        },
        {
          toggleLabel: "since Dencun (2024-03-13)",
          type: "line",
          title: "Gas Usage & Fees Since Dencun",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1746576000000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Pectra",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
          caption: "Data: growthepie.com quick-bite fusaka timeseries gas (Dencun window).",
        },
      ],
    }),
    "```",

    "## Totals to Date",
    "```kpi-cards",
    JSON.stringify([
      {
        title: "Total Blobs",
        value: "{{fusaka_total_blobs}}",
        description: "since Dencun (128 KB each)",
        icon: "gtp-da-blobs-number",
        info: "Each blob can store up to 128 KB; cumulative blobs posted since Dencun.",
      },
      {
        title: "Blob Fees Paid",
        value: "Ξ{{fusaka_total_blob_fees_eth}}",
        description: "cumulative blob base fees",
        icon: "gtp-realtime",
        info: "Total blob base fees paid across the tracked upgrade windows.",
      },
    ]),
    "```",

    "```chart",
    JSON.stringify({
      type: "area",
      title: "Blob Burn vs Gas Burn",
      subtitle: "The share of Burn that is coming from Blob Fees vs Gas Fees",
      showXAsDate: true,
      dataAsJson: {
        meta: [
          {
            name: "Blob Burn",
            color: "#1DF7EF",
            stacking: "percent",
            xIndex: 0,
            yIndex: 3,
            suffix: null,
            prefix: 'Ξ',
            tooltipDecimals: 2,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
            pathToData: "data.timeseries.values",
          },
          {
            name: "Gas Burn",
            color: "#FFDF27",
            stacking: "percent",
            xIndex: 0,
            yIndex: 3,
            suffix: null,
            prefix: 'Ξ',
            tooltipDecimals: 2,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
            pathToData: "data.timeseries.values",
          }
        ],
      },
      height: 500,
      caption: "The share of Blob Burn vs Gas Burn. Data updated daily."
    }),
    "```",




    "# EIP-7918 Deep Dive",
    "EIP-7918 introduces a new blob fee path. Track how it impacts median blob gas fees on a log scale, and compare cumulative fees with/without the upgrade.",
    "```kpi-cards",
    JSON.stringify([
      {
        title: "Blob Fees",
        value: "Ξ{{fusaka_total_blob_fee_eth_with7918}}",
        description: "since Pectra",
        icon: "gtp-realtime",
        info: "Total blob base fees paid under the 7918 blob fee path.",
      },
      {
        title: "Blob Fees without EIP-7918",
        value: "Ξ{{fusaka_total_blob_fee_eth_without7918}}",
        description: "since Pectra",
        icon: "gtp-realtime",
        info: "Estimated blob base fees if 7918 were not active.",
      }
    ]),
    "```",

    "```chart",
    JSON.stringify({
      type: "line",
      title: "Median Blob Gas Fee",
      subtitle: "Comparing the new EIP-7918 excess blob gas calculation vs. the old blob gas path.",
      showXAsDate: true,
      options: {
        yAxis: [{ type: "logarithmic" }],
      },
      dataAsJson: {
        meta: [
          {
            name: "With EIP-7918",
            color: "#00c805",
            type: "line",
            xIndex: 0,
            yIndex: 1,
            suffix: " gwei",
            tooltipDecimals: 9,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/eip7918_timeseries.json",
            pathToData: "data.timeseries.values",
          },
          {
            name: "Without EIP-7918",
            color: "#FE5468",
            type: "line",
            dashStyle: "Dash",
            xIndex: 0,
            yIndex: 3,
            suffix: " gwei",
            tooltipDecimals: 9,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/eip7918_timeseries.json",
            pathToData: "data.timeseries.values",
          },
        ],
      },
      height: 500,
      yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#FFFFFF",
              textColor: "#FFFFFF",
              textFontSize: "9px",
              backgroundColor: "#FFFFFF",
              lineWidth: 1,
            },
          ],
      caption: "Median blob base fee with (index 1) and without (index 3) EIP-7918; log y-axis.",
    }),
    "```",

    "> This page is a data tracker for informational and educational purposes only. It is not investment advice. Data may be delayed or inaccurate. Do your own research.",
  ],
  image: "https://api.growthepie.com/v1/quick-bites/banners/fusaka.png",
  og_image: "",
  date: "2025-12-16",
  related: [],
  author: [{
    name: "Lorenz Lehmann",
    xUsername: "LehmannLorenz",
  },
  {
    name: "ETH Wave",
    xUsername: "TrueWaveBreak"
  }],
  topics: [
    {
      icon: "ethereum-logo-monochrome",
      color: "#94ABD3",
      name: "Ethereum Mainnet",
      url: "/chains/ethereum"
    },
    {
      icon: "gtp-metrics-economics",
      name: "Economics",
      url: "/economics"
    },
    {
      icon: "gtp-data-availability",
      name: "Data Availability",
      url: "/data-availability"
    },
  ],
  icon: "",
  showInMenu: false
};

export default Fusaka;
