// In your quick bite data file (e.g., lib/quick-bites/linea-token-burn.ts)
import { QuickBiteData } from '@/lib/types/quickBites';
import { prefetchDNS } from 'react-dom';

const Fusaka: QuickBiteData = {
  title: "Fusaka Upgrade: Committing to Sustained Scaling",
  shortTitle: "Fusaka Upgrade",
  subtitle: "Expanding Ethereum’s throughput while preserving fee stability",
  content: [
    "# Introduction:",
    "Activated on December 3rd, 2025 and including 12 EIPs, the Fusaka upgrade advances both Ethereum’s L1 scaling and its blob scaling roadmap. Fusaka also signals Ethereum’s commitment to sustainable fee dynamics and the long-term monetization of blobs.",

    "# Scaling Blobs", 
    "Fusaka scales blob capacity through Blob-Parameter-Only (BPO) upgrades (EIP-7892), specifically BPO1 and BPO2. These updates are complemented by PeerDAS (EIP-7594), which introduces Peer Data Availability Sampling. While BPO increases the target blob count, PeerDAS ensures the network can handle this increased data load by allowing nodes to verify blobs without downloading them in their entirety.",
    "BPO upgrades are lightweight protocol updates that adjust only blob-related parameters without introducing broader execution or consensus changes. These upgrades increase Ethereum’s data availability capacity, supporting rollups and other L2 systems that rely on blobs for data availability. BPO1 activated on the 9th of December 2025, increasing the target blob count per block from 6 to 10 (with a maximum of 15). BPO2 activated on the 7th of January 2026, further raising the target from 10 to 14 blobs per block (with a maximum of 21).", 

    "```chart-toggle",
    JSON.stringify({
      title: null,
      description: "Select Timeframe",
      layout: "segmented",
      defaultIndex: 2,
      charts: [
        {
          toggleLabel: "since Fusaka-BPO2 (2026-01-07)",
          type: "line",
          title: "Is Blob Capacity Since Fusaka-BPO2 Keeping Up with Demand?",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [],
          caption: "Fusaka-BPO1 & BPO2 increase blob targets, enabling more data availability capacity for L2s.",
        },
        {
          toggleLabel: "since Fusaka-BPO1 (2025-12-09)",
          type: "line",
          title: "Is Blob Capacity Since Fusaka-BPO1 Keeping Up with Demand?",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1767747695000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO2",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            }
          ],
          caption: "Fusaka-BPO1 & BPO2 increase blob targets, enabling more data availability capacity for L2s.",
        },
        {
          toggleLabel: "since Fusaka (2025-12-03)",
          type: "line",
          title: "Is Blob Capacity Since Fusaka Keeping Up with Demand?",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1765281600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO1",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
            {
              xValue: 1767747695000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO2",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            }
          ],
          caption: "Fusaka-BPO1 & BPO2 increase blob targets, enabling more data availability capacity for L2s.",
        },
        {
          toggleLabel: "since Pectra (2025-05-07)",
          type: "line",
          title: "Is Blob Capacity Since Pectra Keeping Up with Demand?",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Pectra.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
          ],
          caption: "Fusaka-BPO1 & BPO2 increase blob targets, enabling more data availability capacity for L2s.",
        },
        {
          toggleLabel: "since Dencun (2024-03-13)",
          type: "line",
          title: "Is Blob Capacity Since Dencun Keeping Up with Demand?",
          subtitle: "Average blobs per block vs target and blob fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg blob count",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Target blob count",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 5,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total blob fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1746576000000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Pectra",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
          ],
          caption: "Fusaka-BPO1 & BPO2 increase blob targets, enabling more data availability capacity for L2s.",
        },
      ],
    }),
    "```",

    "# Scaling L1 Gas",
    "EIP-7935 set the default L1 block gas limit to 60M (implying a 30M target); however, the network reached this level shortly before the fork via validator signaling, which allows gradual gas limit adjustments independent of hard-fork activation.",

    "```chart-toggle",
    JSON.stringify({
      title: null,
      description: "Select Timeframe",
      layout: "segmented",
      defaultIndex: 3,
      charts: [
        {
          toggleLabel: "since Fusaka-BPO2 (2026-01-07)",
          type: "line",
          title: "Can We Scale L1 Gas Fast Enough Since Fusaka-BPO2 to Lower Fees?",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO2.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [],
          caption: "Fusaka enabled higher L1 execution capacity through an increased gas limit.",
        },
        {
          toggleLabel: "since Fusaka-BPO1 (2025-12-09)",
          type: "line",
          title: "Can We Scale L1 Gas Fast Enough Since Fusaka-BPO1 to Lower Fees?",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka-BPO1.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1767747695000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO2",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            }
          ],
          caption: "Fusaka enabled higher L1 execution capacity through an increased gas limit.",
        },
        {
          toggleLabel: "since Fusaka (2025-12-03)",
          type: "line",
          title: "Can We Scale L1 Gas Fast Enough Since Fusaka to Lower Fees?",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                suffix: null,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Fusaka.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1765281600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO1",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
            {
              xValue: 1767747695000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka-BPO2",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            }
          ],
          caption: "Fusaka enabled higher L1 execution capacity through an increased gas limit.",
        },
        {
          toggleLabel: "since Pectra (2025-05-07)",
          type: "line",
          title: "Can We Scale L1 Gas Fast Enough Since Pectra to Lower Fees?",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Pectra.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
          ],
          caption: "Fusaka enabled higher L1 execution capacity through an increased gas limit.",
        },
        {
          toggleLabel: "since Dencun (2024-03-13)",
          type: "line",
          title: "Can We Scale L1 Gas Fast Enough Since Dencun to Lower Fees?",
          subtitle: "Average gas per block vs max gas and base gas fees in ETH.",
          showXAsDate: true,
          dataAsJson: {
            meta: [
              {
                name: "Avg gas used",
                color: "#FFC300",
                type: "line",
                xIndex: 0,
                yIndex: 1,
                tooltipDecimals: 2,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Gas limit",
                color: "#19D9D6",
                type: "line",
                dashStyle: "Dash",
                xIndex: 0,
                yIndex: 2,
                tooltipDecimals: 0,
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
              {
                name: "Total base gas fees",
                color: "#FE5468",
                type: "line",
                oppositeYAxis: true,
                xIndex: 0,
                yIndex: 4,
                tooltipDecimals: 4,
                prefix: 'Ξ',
                url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
                pathToData: "data.timeseries.values",
              },
            ],
          },
          height: 500,
          yAxisLine: [
            {
              xValue: 1746576000000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Pectra",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
          ],
          caption: "Fusaka enabled higher L1 execution capacity through an increased gas limit.",
        },
      ],
    }),
    "```",

    "# Sustainable Economics for Blobs",
    "Historically, the majority of ETH burned has come from L1 gas fees. With the introduction of blob fees, Ethereum added a second onchain burn mechanism. While blob-related burn is currently small relative to execution gas fees, it is growing as blob usage scales. Fusaka reinforces Ethereum’s commitment to the long-term monetization of blobs, ensuring that increased blob adoption contributes to the network’s economic sustainability.", 

    "```kpi-cards",
    JSON.stringify([
      {
        title: "Total Blobs",
        value: "{{fusaka_total_blobs}}",
        description: "since Dencun (128 KB each)",
        icon: "gtp-da-blobs-number",
        info: "Each blob can store up to 128 KB; total blobs posted since Dencun.",
      },
      {
        title: "Blob Fees Paid",
        value: "Ξ{{fusaka_total_blob_fees_eth}}",
        description: "blob base fees since Dencun",
        icon: "gtp-realtime",
        info: "Total blob base fees paid & burnt since Dencun.",
      },
    ]),
    "```",

    "```chart",
    JSON.stringify({
      type: "area",
      title: "How Much Do Blobs Actually Contribute to the ETH Burn?",
      subtitle: "The share of burn that is coming from blob fees vs gas fees",
      showXAsDate: true,
      dataAsJson: {
        meta: [
          {
            name: "Blob Base Fees",
            color: "#1DF7EF",
            stacking: "percent",
            xIndex: 0,
            yIndex: 3,
            suffix: null,
            prefix: 'Ξ',
            tooltipDecimals: 2,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_blobs/Dencun.json",
            pathToData: "data.timeseries.values",
          },
          {
            name: "Gas Base Fees",
            color: "#FFDF27",
            stacking: "percent",
            xIndex: 0,
            yIndex: 3,
            suffix: null,
            prefix: 'Ξ',
            tooltipDecimals: 2,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/timeseries_gas/Dencun.json",
            pathToData: "data.timeseries.values",
          }
        ],
      },
      height: 500,
      caption: "The share of ETH burned from blob base fees remains relatively small compared to execution gas base fees since Dencun.",
    }),
    "```",




    "## EIP-7918 Deep Dive",
    "EIP-7918 introduces a floor on blob gas price by bounding the blob base fee to execution gas prices, ensuring that the cost of 'GAS_PER_BLOB' blob gas cannot fall below the equivalent execution cost ('BLOB_BASE_COST' × 'base_fee_per_gas'). When this floor binds, excess blob gas accumulates without subtracting the target, tightening the blob fee market and anchoring blob pricing to L1 execution economics.",
    
    "```kpi-cards",
    JSON.stringify([
      {
        title: "Blob Fees",
        value: "Ξ{{fusaka_total_blob_fee_eth_with7918}}",
        description: "since Fusaka",
        icon: "gtp-realtime",
        info: "Total blob base fees paid under the 7918 blob fee path.",
      },
      {
        title: "Blob Fees without EIP-7918",
        value: "Ξ{{fusaka_total_blob_fee_eth_without7918}}",
        description: "since Fusaka",
        icon: "gtp-realtime",
        info: "Estimated blob base fees if 7918 were not active.",
      },
      {
        title: "Multiplier Effect",
        value: "{{fusaka_total_blob_fee_eth_multiplier}}x",
        description: "more blob fees with EIP-7918",
        icon: "gtp-realtime",
        info: "",
      }
    ]),
    "```",

    "```chart",
    JSON.stringify({
      type: "line",
      title: "Is EIP-7918 Successfully Ending the 'Zero-Fee' Blob Era?",
      subtitle: "Comparing the new EIP-7918 excess blob gas calculation vs. the old blob gas path.",
      showXAsDate: true,
      options: {
        yAxis: [{ type: "logarithmic" }],
      },
      dataAsJson: {
        meta: [
          {
            name: "With EIP-7918",
            color: "#00c805",
            type: "line",
            xIndex: 0,
            yIndex: 1,
            suffix: " gwei",
            tooltipDecimals: 9,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/eip7918_timeseries.json",
            pathToData: "data.timeseries.values",
          },
          {
            name: "Without EIP-7918",
            color: "#FE5468",
            type: "line",
            dashStyle: "Dash",
            xIndex: 0,
            yIndex: 3,
            suffix: " gwei",
            tooltipDecimals: 9,
            url: "https://api.growthepie.com/v1/quick-bites/fusaka/eip7918_timeseries.json",
            pathToData: "data.timeseries.values",
          },
        ],
      },
      height: 500,
      yAxisLine: [
            {
              xValue: 1764777600000,
              annotationPositionY: -8,
              annotationPositionX: 0,
              annotationText: "Fusaka",
              lineStyle: "Dash",
              lineColor: "#CDD8D3",
              textColor: "#CDD8D3",
              textFontSize: "9px",
              backgroundColor: "#CDD8D3",
              lineWidth: 1,
            },
          ],
      caption: "Under EIP-7918, blob gas price are bounded by execution costs; the resulting fee floor is clearly observable relative to the legacy blob fee path.",
    }),
    "```",

    "> This page is a data tracker for informational and educational purposes only. It is not investment advice. Data may be delayed or inaccurate. Do your own research.",
  ],
  image: "https://api.growthepie.com/v1/quick-bites/banners/fusaka.png",
  og_image: "",
  date: "2025-12-17",
  related: [],
  author: [{
    name: "Lorenz Lehmann",
    xUsername: "LehmannLorenz",
  },
  {
    name: "ETH Wave",
    xUsername: "TrueWaveBreak"
  }],
  topics: [
    {
      icon: "ethereum-logo-monochrome",
      color: "#94ABD3",
      name: "Ethereum Mainnet",
      url: "/chains/ethereum"
    },
    {
      icon: "gtp-metrics-economics",
      name: "Economics",
      url: "/economics"
    },
    {
      icon: "gtp-data-availability",
      name: "Data Availability",
      url: "/data-availability"
    },
  ],
  icon: "",
  showInMenu: true
};

export default Fusaka;
