import { QuickBiteData } from '@/lib/types/quickBites';
import { createQuickBite } from '@/lib/quick-bites/createQuickBite';

const octantV2Migration: QuickBiteData = createQuickBite({
  title: "Octant v2 Migration Guide",
  shortTitle: "Octant v2 Move",
  subtitle: "Move to Octant v2 early to keep rewards flowing and unlock the upgraded experience",
  summary:
    "A migration walkthrough plus core Octant context, including locked-wallet and project funding data across epochs.",
  content: [
    "# Octant v2 migration is open",
    "Make your move now at [octant.app](https://octant.app). Migrating early helps maximize rewards under the new time-weighted system.",
    "```image",
    JSON.stringify({
      src: "https://api.growthepie.com/v1/quick-bites/banners/Octant-v2-Migration-banner.png",
      alt: "Octant v2 Migration banner",
      width: "1200",
      height: "675",
      caption: "Octant v2 migration campaign",
    }),
    "```",
    "## What Octant is",
    "Octant is a public-goods funding system powered by locked GLM. Users lock GLM, earn rewards, and allocate ETH to projects each epoch. Matching then amplifies impact based on community participation. You can explore the full tracker here: [growthepie Octant Tracker](https://growthepie.com/trackers/octant).",
    "",
    "## Octant at a glance",
    "```kpi-cards",
    JSON.stringify([
      {
        title: "Total Funded",
        value: "{{octant_total_funded_eth}} ETH",
        description: "across all epochs",
        icon: "gtp-project",
        info: "Funding paid out from donations and matching.",
      },
      {
        title: "Median Project Funding",
        value: "{{octant_median_project_funding_eth}} ETH",
        description: "across all epochs",
        icon: "gtp-realtime",
        info: "Median project payout in the Octant tracker.",
      },
      {
        title: "Wallets with GLM Locked",
        value: "{{octant_total_wallets_locked}}",
        description: "current total",
        icon: "gtp-users",
        info: "Unique wallets currently locking GLM in Octant.",
      },
    ]),
    "```",
    "> These KPIs are pulled from the live Octant tracker dataset.",
    "",
    "## Octant participation across epochs",
    "The chart below shows how many wallets had GLM locked in each started epoch, alongside total GLM locked.",
    "```chart",
    JSON.stringify({
      type: "line",
      title: "Locked GLM Participation by Epoch",
      subtitle: "Wallets with locked GLM and total GLM locked",
      showXAsDate: true,
      dataAsJson: {
        meta: [
          {
            name: "Wallets with GLM locked",
            color: "#19D9D6",
            type: "column",
            xIndex: 0,
            yIndex: 2,
            tooltipDecimals: 0,
            url: "/api/quick-bites/octant-migration",
            pathToData: "data.locked_by_epoch.rows",
          },
          {
            name: "Total GLM locked",
            color: "#FE5468",
            type: "line",
            oppositeYAxis: true,
            xIndex: 0,
            yIndex: 3,
            tooltipDecimals: 0,
            url: "/api/quick-bites/octant-migration",
            pathToData: "data.locked_by_epoch.rows",
          },
        ],
      },
      height: 440,
      caption: "Source: growthepie Octant tracker aggregates.",
    }),
    "```",
    "",
    "## Top funded projects (donations + matching, all epochs)",
    "This table highlights where capital has flowed the most when combining direct donations with matching.",
    "```table",
    JSON.stringify({
      readFromJSON: true,
      jsonData: {
        url: "/api/quick-bites/octant-migration",
        pathToRowData: "data.top_projects_all.rows",
        pathToColumnKeys: "data.top_projects_all.columns",
      },
      columnDefinitions: {
        project_name: {
          label: "Project",
          type: "string",
          minWidth: 220,
          isNumeric: false,
          sortByValue: true,
          expand: true,
        },
        allocations_all: {
          label: "Donations (ETH)",
          type: "number",
          minWidth: 110,
          isNumeric: true,
          sortByValue: true,
          units: { value: { decimals: 2 } },
        },
        matching_all: {
          label: "Matching (ETH)",
          type: "number",
          minWidth: 110,
          isNumeric: true,
          sortByValue: true,
          units: { value: { decimals: 2 } },
        },
        total_funding_all: {
          label: "Total Funding (ETH)",
          type: "number",
          minWidth: 120,
          isNumeric: true,
          sortByValue: true,
          units: { value: { decimals: 2 } },
        },
        donors_all: {
          label: "Unique Donors",
          type: "number",
          minWidth: 100,
          isNumeric: true,
          sortByValue: true,
          units: { value: { decimals: 0 } },
        },
      },
      columnOrder: [
        "project_name",
        "allocations_all",
        "matching_all",
        "total_funding_all",
        "donors_all",
      ],
      columnSortBy: "value",
    }),
    "```",
    "",
    "# Why migrating matters",
    "Epoch 11 is the final epoch on the current Octant version. After **March 4, 2026**, new rewards are generated only on Octant v2.",
    "The upgraded version is designed to support more flexible funding-round timing instead of being tied to a fixed 90-day cycle, alongside deeper improvements under the hood.",
    "During Epoch 11, users can allocate ETH to themselves, to Protocol Guild, or split between both. Allocations to Protocol Guild in this epoch do not receive matching funds.",
    "",
    "## What's changing for users",
    "The core model stays non-custodial: you keep control of your GLM and can still unlock, increase, or decrease your lock.",
    "Rewards are now time-weighted, so earlier migration generally means higher reward capture. The v2 flow also improves UX and prepares the app for more flexible future rounds.",
    "",
    "## 4-step migration process",
    "1. Withdraw any unclaimed ETH from the previous epoch.",
    "2. Complete your Epoch 11 allocation (self, Protocol Guild, or both).",
    "3. Click **Migrate** on the Octant homepage.",
    "4. Confirm 2 transactions: unlock on current version, then lock on v2 (typically ~5 minutes total, plus gas).",
    "",
    "# Critical points",
    "If you do not migrate, ETH rewards stop after Epoch 11 and you cannot participate in future rounds on the upgraded system.",
    "You can still migrate after March 4, 2026, but any delay means missing rewards during that period.",
    "> More details, screenshots, and troubleshooting guidance are coming soon.",
    "",
    "",
  ],
  image:
    "https://api.growthepie.com/v1/quick-bites/banners/Octant-v2-Migration-banner.png",
  date: "2026-02-23",
  icon: "gtp-realtime",
  related: ["/chains/ethereum"],
  author: [{
    name: "Tobias Schreier",
    xUsername: "tobschcom",
  }],
  topics: [
    {
      icon: "ethereum-logo-monochrome",
      color: "#94ABD3",
      name: "Ethereum Mainnet",
      url: "/chains/ethereum"
    },
  ],
});

export default octantV2Migration;