export default function Head() {
  return (
    <>
      <title>Grow The Pie - L2 Metrics - Track the layer two ecosystem</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="preconnect" href="https://rsms.me/" />
    </>
  );
}
