import React, { useMemo } from 'react';
import { GTPIcon } from '../GTPIcon';
import Container from '../Container';
import useSWR from 'swr';
import { EthAggURL } from '@/lib/urls';
import { EthAggResponse, CountLayer2s, Tps, Stables, Gdp, MeetL2s } from '@/types/api/EthAggResponse';
import "@/app/highcharts.axis.css";
import { useLocalStorage } from "usehooks-ts";
import { useMaster } from "@/contexts/MasterContext";
import { GTPIconName } from "@/icons/gtp-icon-names";
import { Icon } from '@iconify/react';
import Link from 'next/link';
import "@/app/highcharts.axis.css";
import { AggChart } from './AggChart';

interface MetricsChartsProps {
  selectedBreakdownGroup: string;
}

export type ChartDataSource = Gdp | Stables | CountLayer2s | Tps | Tps['layer_2s'];

export interface SeriesConfig {
  dataExtractor: (data: ChartDataSource, showUsd: boolean) => [number, number][];
  type: 'area' | 'column';
  key: string;
  name?: string;
  stacking?: 'normal' | 'x' | undefined;
}

export interface AggChartProps {
  title: string;
  tooltipContent: string;
  prefix: string;
  dataSource: ChartDataSource;
  seriesConfigs: SeriesConfig[];
  totalValueExtractor: (data: ChartDataSource, showUsd: boolean) => string;
  shareValueExtractor?: (data: ChartDataSource, showUsd: boolean) => string;
}

// Optimized shared formatting function
const formatNumber = (number: number, decimals = 2): string => {
  if (number === 0) return "0";
  
  const absNumber = Math.abs(number);
  if (absNumber >= 1e12) return (number / 1e12).toFixed(2) + "T";
  if (absNumber >= 1e9) return (number / 1e9).toFixed(2) + "B";
  if (absNumber >= 1e6) return (number / 1e6).toFixed(2) + "M";
  if (absNumber >= 1e3) return (number / 1e3).toFixed(2) + "k";
  if (absNumber >= 100) return number.toFixed(decimals);
  return number.toFixed(decimals);
};

function MetricsChartsComponent({ selectedBreakdownGroup }: MetricsChartsProps) {
  const { data, error, isLoading } = useSWR<EthAggResponse>(EthAggURL);
  const [showUsd] = useLocalStorage("showUsd", true);
  const { AllChainsByKeys } = useMaster();

  // Memoized data extraction
  const chartData = useMemo(() => {
    if (!data) return null;
    
    return {
      stableData: data.data.stables,
      appData: data.data.app_fees,
      layer2Data: data.data.count_layer2s,
      tpsData: data.data.tps,
      meetL2sData: data.data.meet_l2s
    };
  }, [data]);

  // Memoized index calculations
  const dataIndices = useMemo(() => {
    if (!chartData) return null;
    
    const appTypes = chartData.appData?.layer_2s?.daily?.types || [];
    const stableTypes = chartData.stableData?.layer_2s?.daily?.types || [];
    const countTypes = chartData.layer2Data?.daily?.types || [];
    const tpsTypes = chartData.tpsData?.layer_2s?.daily?.types || [];

    return {
      app: {
        unix: appTypes.indexOf("unix"),
        usd: appTypes.indexOf("usd"),
        eth: appTypes.indexOf("eth")
      },
      stable: {
        unix: stableTypes.indexOf("unix"),
        usd: stableTypes.indexOf("usd"),
        eth: stableTypes.indexOf("eth")
      },
      count: {
        unix: countTypes.indexOf("unix"),
        value: countTypes.indexOf("value"),
        launched: countTypes.indexOf("l2s_launched")
      },
      tps: {
        unix: tpsTypes.indexOf("unix"),
        value: tpsTypes.indexOf("value")
      }
    };
  }, [chartData]);

  // Memoized chart configurations
  const chartConfigs = useMemo(() => {
    if (!chartData || !dataIndices) return null;

    const { app, stable, count, tps } = dataIndices;
    const prefix = showUsd ? "$" : "Ξ";

    return {
      appRevenue: {
        title: "Application Revenue",
        tooltipContent: "Application Revenue is the total revenue generated by applications built on Ethereum, including Layer 2s and Ethereum Mainnet.",
        prefix,
        seriesConfigs: [
                     {
             name: "Ethereum Mainnet",
             key: "ethereum",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data, showUsd) => (data as Gdp).ethereum_mainnet.daily.values.map(v => [v[app.unix], v[showUsd ? app.usd : app.eth]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
           {
             name: "Layer 2s",
             key: "all_l2s",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data, showUsd) => (data as Gdp).layer_2s.daily.values.map(v => [v[app.unix], v[showUsd ? app.usd : app.eth]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
        ],
        totalValueExtractor: (data, showUsd) => {
          const d = data as Gdp;
          const key = showUsd ? app.usd : app.eth;
          const total = d.layer_2s.daily.values.slice(-1)[0][key] + d.ethereum_mainnet.daily.values.slice(-1)[0][key];
          return `${prefix}${formatNumber(total)}`;
        },
        shareValueExtractor: (data, showUsd) => {
          const d = data as Gdp;
          const key = showUsd ? app.usd : app.eth;
          const l2 = d.layer_2s.daily.values.slice(-1)[0][key];
          const total = l2 + d.ethereum_mainnet.daily.values.slice(-1)[0][key];
          return `Layer 2 Share: ${((l2 / total) * 100).toFixed(2)}%`;
        },
      },
      stablecoin: {
        title: "Stablecoin Supply",
        tooltipContent: "Stablecoin Supply is the total supply of stablecoins on Ethereum, including Layer 2s and Ethereum Mainnet.",
        prefix,
        seriesConfigs: [
                     {
             name: "Ethereum Mainnet",
             key: "ethereum",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data, showUsd) => (data as Stables).ethereum_mainnet.daily.values.map(v => [v[stable.unix], v[showUsd ? stable.usd : stable.eth]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
           {
             name: "Layer 2s",
             key: "all_l2s",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data, showUsd) => (data as Stables).layer_2s.daily.values.map(v => [v[stable.unix], v[showUsd ? stable.usd : stable.eth]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
        ],
        totalValueExtractor: (data, showUsd) => {
          const d = data as Stables;
          const key = showUsd ? stable.usd : stable.eth;
          const total = d.layer_2s.daily.values.slice(-1)[0][key] + d.ethereum_mainnet.daily.values.slice(-1)[0][key];
          return `${prefix}${formatNumber(total)}`;
        },
        shareValueExtractor: (data, showUsd) => {
          const d = data as Stables;
          const key = showUsd ? stable.usd : stable.eth;
          const l2 = d.layer_2s.daily.values.slice(-1)[0][key];
          const total = l2 + d.ethereum_mainnet.daily.values.slice(-1)[0][key];
          return `Layer 2 Share: ${((l2 / total) * 100).toFixed(2)}%`;
        }
      },
      l2Count: {
        title: "Layer 2s Building on Ethereum",
        tooltipContent: "Layer 2s are scaling solutions built on Ethereum to increase transaction throughput and reduce fees.",
        prefix: "",
        seriesConfigs: [
                     {
             name: "Total L2s",
             key: "total_l2s",
             type: 'column' as const,
             dataExtractor: ((data) => (data as CountLayer2s).daily.values.map(v => [v[count.unix], v[count.value]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
           {
             name: "L2s Launched",
             key: "l2s_launched",
             type: 'column' as const,
             dataExtractor: ((data) => (data as CountLayer2s).daily.values.map(v => [v[count.unix], v[count.launched]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           }
        ],
        totalValueExtractor: (data) => formatNumber((data as CountLayer2s).daily.values.slice(-1)[0][count.value]),
      },
      tps: {
        title: "Average Daily TPS",
        tooltipContent: "Average Daily TPS is the average number of transactions per second across the Ethereum ecosystem.",
        prefix: "",
        seriesConfigs: [
                     {
             name: "Ethereum Mainnet",
             key: "ethereum",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data) => (data as Tps).ethereum_mainnet.daily.values.map(v => [v[tps.unix], v[tps.value]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
           {
             name: "Layer 2s",
             key: "all_l2s",
             type: 'area' as const,
             stacking: 'x' as const,
             dataExtractor: ((data) => (data as Tps).layer_2s.daily.values.map(v => [v[tps.unix], v[tps.value]] as [number, number])) as (data: ChartDataSource, showUsd: boolean) => [number, number][],
           },
        ],
        totalValueExtractor: (data) => {
          const d = data as Tps;
          const total = d.layer_2s.daily.values.slice(-1)[0][tps.value] + d.ethereum_mainnet.daily.values.slice(-1)[0][tps.value];
          return formatNumber(total);
        }
      }
    };
  }, [chartData, dataIndices, showUsd]);

  if (selectedBreakdownGroup !== "Metrics") return null;
  if (!chartData || !chartConfigs) return null;

  return (
    <Container className='flex flex-col gap-y-[60px] mt-[60px] w-full'>
      <div className='flex flex-col gap-y-[15px]'>
        <div className='flex gap-x-[8px] items-center'>
          <GTPIcon icon='gtp-metrics-economics' size='lg' className='text-[#5A6462]' />
          <div className='heading-large-lg'>Economic Activity is Shifting Onchain</div>
        </div>
        <div className='pl-[45px] text-md'>Value locked and user spending are growing across the Ethereum ecosystem, with Ethereum Mainnet remaining the most trusted ledger.</div>
        <div className='flex flex-col xl:flex-row gap-[15px] w-full'>
          <AggChart dataSource={chartData.appData} {...chartConfigs.appRevenue} />
          <AggChart dataSource={chartData.stableData} {...chartConfigs.stablecoin} />
        </div>
      </div>
      <div className='flex flex-col gap-y-[15px]'>
        <div className='flex gap-x-[8px] items-center'>
          <GTPIcon icon='gtp-ecosystem-scaling' size='lg' className='text-[#5A6462]' />
          <div className='heading-large-lg'>The Ethereum Ecosystem is Scaling</div>
        </div>
        <div className='pl-[45px] text-md'>Transaction throughput is rising across Ethereum Mainnet and its growing number of Layer 2 networks.</div>
        <div className='flex flex-col xl:flex-row gap-[15px] w-full'>
          <AggChart dataSource={chartData.layer2Data} {...chartConfigs.l2Count} />
          <AggChart dataSource={chartData.tpsData} {...chartConfigs.tps} />
        </div>
      </div>
      <MeetLayer2s meetL2sData={chartData.meetL2sData} selectedBreakdownGroup={selectedBreakdownGroup} />
    </Container>
  );
}

const MeetLayer2s = React.memo(({ meetL2sData, selectedBreakdownGroup }: { meetL2sData: MeetL2s | null, selectedBreakdownGroup: string }) => {
  const { AllChainsByKeys } = useMaster();
  const [showUsd] = useLocalStorage("showUsd", true);

  const l2Keys = useMemo(() => meetL2sData ? Object.keys(meetL2sData) : [], [meetL2sData]);

  if (!meetL2sData || selectedBreakdownGroup !== "Metrics") return null;

  return (
    <div className="flex flex-col gap-y-[15px] w-full overflow-hidden">
      <div className='flex gap-x-[8px] items-center'>
        <GTPIcon icon='gtp-multiple-chains' size='lg' />
        <div className='heading-large-lg'>Meet L2s</div>
      </div>
      <div className='text-md pl-[44px] overflow-hidden'>Ethereum scales using different Layer 2s, built by 3rd party teams. Have a closer look at each of them.</div>
      <div className='flex w-full gap-[5px] overflow-hidden'>
        {l2Keys.map((key) => {
          const l2Data = meetL2sData[key];
          const chainInfo = AllChainsByKeys[key];
          const color = chainInfo?.colors?.dark?.[0];

          return (
            <div key={key} className='flex flex-col gap-y-[10px] rounded-[15px] p-[15px] bg-transparent border-[1px] border-[#5A6462] flex-shrink-0 w-full sm:w-[calc(50%-2.5px)] lg:w-[calc(33.333%-3.33px)] xl:w-[calc(25%-3.75px)] 2xl:w-[calc(20%-4px)]'>
              <div className='flex items-center w-full justify-between'>
                <div className='flex items-center gap-x-[5px]'>
                  <GTPIcon 
                    icon={`${chainInfo?.urlKey}-logo-monochrome` as GTPIconName} 
                    size='lg'
                    style={{ color }}
                  />
                  <div className='heading-large-md'>{chainInfo?.label}</div>
                </div>
                <Link href={`/chains/${key}`} className='flex items-center justify-center w-[24px] h-[24px] rounded-full bg-[#344240]'>
                  <Icon icon="feather:arrow-right" className="w-[15px] h-[15px]" />
                </Link>
              </div>
              <div className='flex gap-x-[10px] items-center'>
                <div className='flex flex-col gap-y-[5px]'>
                  <div className='numbers-2xl'>{formatNumber(l2Data.yesterday_aa)}</div>
                  <div className='text-xs'>Wallets Yesterday</div>
                </div>
                <div className='flex flex-col gap-y-[5px]'>
                  <div className='numbers-2xl'>{formatNumber(l2Data.total_aa)}</div>
                  <div className='text-xs'>Total Wallets</div>
                </div>
              </div>
              <div className='flex gap-x-[10px] items-center'>
                <div className='flex flex-col gap-y-[5px]'>
                  <div className='numbers-2xl'>{formatNumber(l2Data[showUsd ? "stables_mcap_usd" : "stables_mcap_eth"])}</div>
                  <div className='text-xs'>Stablecoin Supply</div>
                </div>
                <div className='flex flex-col gap-y-[5px]'>
                  <div className='numbers-2xl'>{formatNumber(l2Data.tps)}</div>
                  <div className='text-xs'>TPS/Day</div>
                </div>
              </div>
              <div className='flex flex-col gap-y-[5px]'>
                <div className='flex items-center gap-x-[5px]'>
                  <GTPIcon icon='gtp-crosschain' size='sm' />
                  <GTPIcon icon='gtp-defi' size='sm' />
                </div>
                <div className='text-xs'>Predominately used for</div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
});

MeetLayer2s.displayName = 'MeetLayer2s';

export default MetricsChartsComponent;