name: Deploy on mokelgit push
on:
  push:
    branches:
    - zircuit
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger rebuild on vercel
        run: curl -X POST ${{ secrets.ZIRCUIT_DEPLOY_HOOK }}
